New Filter + Modifications
PaperFanz/iort_filters pull request #1
Opened 2021-07-30 15:46 UTC by sidharthNair

Made some changes to existing filter + added a new filter (MQTTOverlay):

- QRFilter now has the capability to dynamically change and reorder which data members are displayed on the overlay by using the insitu edit filter option. The text will scale with the amount of data members being displayed.
![New Interface](https://user-images.githubusercontent.com/84476225/127677929-bfc9c1bb-5b98-4aa8-afb2-05dc989a4988.png)
- MQTTOverlay is a new filter that works similarly to QRFilter but allows the user to manually input the device UUID to subscribe to and overlay the data wherever they want on the screen. Makes use of the new settings feature on insitu which will allow the user to save the size and location of the overlay. Data member selection is the same as with QRFilter.

2021-07-31 17:40 UTC, PaperFanz requested changes
Looks great but needs to be using OpenCV 3

2021-07-31 17:40 UTC, PaperFanz commented on CMakeLists.txt
> +find_package(OpenCV 4.2.0 REQUIRED)
OpenCV 4 is not supported in ROS Melodic and may cause issues with other ROS applications

2021-07-31 18:21 UTC, sidharthNair commented
I see, I was using this with Noetic which I believe only supports 4.2.0 and I forgot that I had changed that. Will change it back

2021-08-02 17:19 UTC, sidharthNair commented
Made some accidental changes without making a new branch. The current version should be good to merge unless further changes need to be made.

2021-08-03 19:17 UTC, merged

2021-08-03 19:19 UTC, PaperFanz reviewed
Looks good!